### ISSUE TITLE
> reticulate::install_python() Error in pyenv_bootstrap_windows() :    Please install git and ensure it is on your PATH

### ISSUE THREAD

**Issue by kyliewyl** [t-kalinowski/tensorflow.rstudio.com#63]

**Comment by t-kalinowski** [comment]
If you see this error message, please install Git. https://git-scm.com/

Alternatively, instead of using `install_python()` (which requires Git), you can install python directly from https://www.python.org/downloads/
Be sure to install a slightly older than the current release version, approx. 2 minor versions behind the current release version. E.g., the current release version is Python 3.12, so you would want to install Python 3.10 for compatibility with the latest TensorFlow version.
